js-todo-list/config/routes.rb
Rails.application.routes.draw do

  root 'tasks#index'

    resources :tasks do
      memeber do
        patch 'swap'
      end
    end

end

js-todo-list/app/models/task.rb
class Task < ActiveRecord::Base

  validates :description, presence: true

  def self.swap(task, direction)
    return if task.placement == 0 ||task.placement == Task.count -1
      current_place = Task.placement
      other_task = Task.find_by(placement: current_place + direction)
      other_place = other_task.placement

end

js-todo-list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

js-todo-list/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.update(placement: Task.count)
    if @task.save
      render json: @task
    else
      render json: @task, status: 500
    end
  end

  def update
    @task = Task.find(params[:id])
    if params[:direction]
      Task.swap(@task, params[:direction].to_i)
    end
  end

  def delete
    Task.find(params[:id]).destroy
    Task.all.order(:placement).each_with_index do |task, index|
      task.update(placement: index)
    end
  end

  private
  def task_params
    params.require(:task).permit(:description, :placement, :completed)
  end

end

js-todo-list/app/helpers/application_helper.rb
module ApplicationHelper
end

js-todo-list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JsTodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

js-todo-list/app/views/tasks/index.html.erb
<h1>My ToDo List Manager!</h1>

<%= form_for @task do |f| %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

<ol>
  <% @tasks.each do |task| %>
  <li>
  <%= task.description %>
  <% if task.placement != 0 %>
  <%= link_to 'up', swap_task_path(task, direction: -1), method: :patch %>
  <% end %>
  
  <% if task!= Task.last %>
  <%= link_to 'down', swap_task_path(task, direction: 1), method: :patch %>
  <% end %>
  </li>
</ol>

<!-- <table>
  <thead>
    <tr>
      <th>Completed?</th>
      <th>Description</th>
      <th>Placement</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <ol>
      <% @tasks.each do |task| %>
    <tr>
      <td><%= task.completed %></td>
      <td><li><%= task.description %></li></td>
      <td> <%= task.placement %> </td>
      <td> Delete Icon </td>
    </tr>
    <% end %>
  </ol>
  </tbody>
</table> -->